In [2]:
import pandas as pd
df = pd.read_csv("1745501008647-data_cleaning_sample.csv")

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [6]:
pd.read_csv("1745501008647-data_cleaning_sample.csv", usecols=["Name", "Age"], nrows=5)

      Name   Age
0    Alice  25.0
1  Charlie   NaN
2      Bob  30.0
3  Charlie   NaN
4    David  22.0

In [9]:
df = df[df['Age']> 22.0]

In [10]:
df

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
5    NaN  28.0        Delhi      F     eve@domain.com         NaN
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [11]:
df.to_csv("data_updates.csv")

In [12]:
df.to_csv("data_updates.csv", index=False)