In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("dataset.csv")

In [3]:
df

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5
0,Actor,Debut Film,Debut Year,Total Films (Approx.),Hit Count (Approx.),Flop Count (Approx.)
1,Shah Rukh Khan,Deewana,1992,65,42,23
2,Salman Khan,Biwi Ho To Aisi,1988,85,50,35
3,Aamir Khan,Qayamat Se Qayamat Tak,1988,46,33,13
4,Akshay Kumar,Saugandh,1991,150,72,78
5,Ajay Devgn,Phool Aur Kaante,1991,115,60,55
6,Hrithik Roshan,Kaho Naa... Pyaar Hai,2000,33,22,11
7,Ranbir Kapoor,Saawariya,2007,22,14,8
8,Ranveer Singh,Band Baaja Baaraat,2010,20,13,7
9,Varun Dhawan,Student of the Year,2012,20,14,6
10,Kartik Aaryan,Pyaar Ka Punchnama,2011,16,10,6

In [5]:
 df.loc[1]

Unnamed: 0    Shah Rukh Khan
Unnamed: 1           Deewana
Unnamed: 2              1992
Unnamed: 3                65
Unnamed: 4                42
Unnamed: 5                23
Name: 1, dtype: object

In [6]:
df.iloc[1]

Unnamed: 0    Shah Rukh Khan
Unnamed: 1           Deewana
Unnamed: 2              1992
Unnamed: 3                65
Unnamed: 4                42
Unnamed: 5                23
Name: 1, dtype: object

In [16]:
df.loc[0, "Debut Year"]

'1992'

In [12]:
import pandas as pd

df = pd.read_csv("dataset.csv")

In [13]:
print(df.columns)

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5'],
      dtype='object')

In [14]:
df.columns = df.iloc[0]   # Make first row the column names
df = df[1:]               # Remove the first row
df.reset_index(drop=True, inplace=True)

In [15]:
df.columns

Index(['Actor', 'Debut Film', 'Debut Year', 'Total Films (Approx.)',
       'Hit Count (Approx.)', 'Flop Count (Approx.)'],
      dtype='object', name=0)

In [17]:
df.iloc[7,5]

'7'

In [18]:
df.loc[0:7],["Actor", "Debut Year"]

(0           Actor              Debut Film Debut Year Total Films (Approx.)  \
 0  Shah Rukh Khan                 Deewana       1992                    65
 1     Salman Khan         Biwi Ho To Aisi       1988                    85
 2      Aamir Khan  Qayamat Se Qayamat Tak       1988                    46
 3    Akshay Kumar                Saugandh       1991                   150
 4      Ajay Devgn        Phool Aur Kaante       1991                   115
 5  Hrithik Roshan   Kaho Naa... Pyaar Hai       2000                    33
 6   Ranbir Kapoor               Saawariya       2007                    22
 7   Ranveer Singh      Band Baaja Baaraat       2010                    20

 0 Hit Count (Approx.) Flop Count (Approx.)
 0                  42                   23
 1                  50                   35
 2                  33                   13
 3                  72                   78
 4                  60                   55
 5                  22                   11
 6                  14                    8
 7                  13                    7  ,
 ['Actor', 'Debut Year'])

In [19]:
df.iloc[0:2,0:2]

0           Actor       Debut Film
0  Shah Rukh Khan          Deewana
1     Salman Khan  Biwi Ho To Aisi

In [20]:
df.at[0,"Actor"]

'Shah Rukh Khan'

In [27]:
df[df['Debut Year']>1992]

,Actor,Debut Film,Debut Year,Total Films (Approx.),Hit Count (Approx.),Flop Count (Approx.)
5,Hrithik Roshan,Kaho Naa... Pyaar Hai,2000,33,22,11
6,Ranbir Kapoor,Saawariya,2007,22,14,8
7,Ranveer Singh,Band Baaja Baaraat,2010,20,13,7
8,Varun Dhawan,Student of the Year,2012,20,14,6
9,Kartik Aaryan,Pyaar Ka Punchnama,2011,16,10,6

In [23]:
print(df.dtypes)

0
Actor                    object
Debut Film               object
Debut Year               object
Total Films (Approx.)    object
Hit Count (Approx.)      object
Flop Count (Approx.)     object
dtype: object

In [24]:
df["Debut Year"] = pd.to_numeric(df["Debut Year"])
df["Total Films (Approx.)"] = pd.to_numeric(df["Total Films (Approx.)"])
df["Hit Count (Approx.)"] = pd.to_numeric(df["Hit Count (Approx.)"])
df["Flop Count (Approx.)"] = pd.to_numeric(df["Flop Count (Approx.)"])

In [25]:
df["Debut Year"] = pd.to_numeric(df["Debut Year"], errors="coerce")

In [26]:
df[df["Debut Year"] > 1992]

,Actor,Debut Film,Debut Year,Total Films (Approx.),Hit Count (Approx.),Flop Count (Approx.)
5,Hrithik Roshan,Kaho Naa... Pyaar Hai,2000,33,22,11
6,Ranbir Kapoor,Saawariya,2007,22,14,8
7,Ranveer Singh,Band Baaja Baaraat,2010,20,13,7
8,Varun Dhawan,Student of the Year,2012,20,14,6
9,Kartik Aaryan,Pyaar Ka Punchnama,2011,16,10,6

In [30]:
df.query("`Debut Year` > 2000")

,Actor,Debut Film,Debut Year,Total Films (Approx.),Hit Count (Approx.),Flop Count (Approx.)
6,Ranbir Kapoor,Saawariya,2007,22,14,8
7,Ranveer Singh,Band Baaja Baaraat,2010,20,13,7
8,Varun Dhawan,Student of the Year,2012,20,14,6
9,Kartik Aaryan,Pyaar Ka Punchnama,2011,16,10,6

In [34]:
df2 = df[['Actor', 'Debut Year']]

In [35]:
df2

0           Actor  Debut Year
0  Shah Rukh Khan        1992
1     Salman Khan        1988
2      Aamir Khan        1988
3    Akshay Kumar        1991
4      Ajay Devgn        1991
5  Hrithik Roshan        2000
6   Ranbir Kapoor        2007
7   Ranveer Singh        2010
8    Varun Dhawan        2012
9   Kartik Aaryan        2011

In [37]:
df2 = df[['Actor', 'Debut Year']].copy()