In [12]:
import pandas as pd
df = pd.read_csv("1745501008647-data_cleaning_sample.csv")

In [13]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [14]:
df.sort_values("Age")

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [15]:
df.sort_values("Age", ascending = False)

      Name   Age         City Gender              Email   Join Date
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [17]:
df2 = df.sort_values(by=["Age", "City"]).copy()
df2

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [15]:
df2

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [18]:
df2.reset_index()

   index     Name   Age         City Gender              Email   Join Date
0      4    David  22.0       Mumbai      M  david@example.com  12-11-2019
1      0    Alice  25.0     New York      F  alice@example.com  01-05-2021
2      6    Alice  25.0     New York      F  alice@example.com  01-05-2021
3      7    Alice  25.0     New York      F  alice@example.com  01-05-2021
4      5      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6      1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
7      3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8      8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [19]:
df2

      Name   Age         City Gender              Email   Join Date
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [20]:
df2.reset_index(drop = True, inplace = True
               )

In [21]:
df2

      Name   Age         City Gender              Email   Join Date
0    David  22.0       Mumbai      M  david@example.com  12-11-2019
1    Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Alice  25.0     New York      F  alice@example.com  01-05-2021
3    Alice  25.0     New York      F  alice@example.com  01-05-2021
4      NaN  28.0        Delhi      F     eve@domain.com         NaN
5      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
6  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
7  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [27]:
df["Rank"] = df2["Age"].rank( ascending = False, method = "dense")

In [25]:
df

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   6.0
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   4.0
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   4.0
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   4.0
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   2.0
5      NaN  28.0        Delhi      F     eve@domain.com         NaN   1.0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021   NaN
7    Alice  25.0     New York      F  alice@example.com  01-05-2021   NaN
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN

In [29]:
df["Rank"] = df["Age"].rank()

In [30]:
df

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   6.0
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0
5      NaN  28.0        Delhi      F     eve@domain.com         NaN   5.0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
7    Alice  25.0     New York      F  alice@example.com  01-05-2021   3.0
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN

In [33]:
df["Rank"] = df["Age"].rank(method="dense")

In [34]:
df.rename(columns={"oldName": "newName"}, inplace=True)

In [35]:
df

      Name   Age         City Gender              Email   Join Date  Rank
0    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   4.0
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
4    David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0
5      NaN  28.0        Delhi      F     eve@domain.com         NaN   3.0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
7    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN

In [36]:
df.rename(index={0: "row1", 1: "row2"}, inplace=True)

In [37]:
df

         Name   Age         City Gender              Email   Join Date  Rank
row1    Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
row2  Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
2         Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020   4.0
3     Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN
4       David  22.0       Mumbai      M  david@example.com  12-11-2019   1.0
5         NaN  28.0        Delhi      F     eve@domain.com         NaN   3.0
6       Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
7       Alice  25.0     New York      F  alice@example.com  01-05-2021   2.0
8     Charlie   NaN        Delhi      M    charlie@example  20-07-2021   NaN

In [38]:
df = df[["City", "Name", "Age"]]   # Reorder as desired

In [39]:
df

             City     Name   Age
row1     New York    Alice  25.0
row2        Delhi  Charlie   NaN
2     Los Angeles      Bob  30.0
3           Delhi  Charlie   NaN
4          Mumbai    David  22.0
5           Delhi      NaN  28.0
6        New York    Alice  25.0
7        New York    Alice  25.0
8           Delhi  Charlie   NaN

In [40]:
cols = ["Name"] + [col for col in df.columns if col != "Name"]

In [41]:
df

             City     Name   Age
row1     New York    Alice  25.0
row2        Delhi  Charlie   NaN
2     Los Angeles      Bob  30.0
3           Delhi  Charlie   NaN
4          Mumbai    David  22.0
5           Delhi      NaN  28.0
6        New York    Alice  25.0
7        New York    Alice  25.0
8           Delhi  Charlie   NaN

In [42]:
df = df[cols]

In [43]:
df

         Name         City   Age
row1    Alice     New York  25.0
row2  Charlie        Delhi   NaN
2         Bob  Los Angeles  30.0
3     Charlie        Delhi   NaN
4       David       Mumbai  22.0
5         NaN        Delhi  28.0
6       Alice     New York  25.0
7       Alice     New York  25.0
8     Charlie        Delhi   NaN