In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [2]:
df.melt(id_vars=None, value_vars=None, var_name=None, value_name="value", col_level=None)

   variable    value
0      Name    Alice
1      Name      Bob
2      Name  Charlie
3      Math       85
4      Math       78
5      Math       92
6   Science       90
7   Science       82
8   Science       89
9   English       88
10  English       85
11  English       94

In [3]:
df.melt(id_vars=["Name"], value_vars=["Math", "Science", "English"], var_name="Subject", value_name="Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [17]:
melted_df = df.melt(
    id_vars=["Name"],
    value_vars=["Math", "Science", "English"],
    var_name="Subject",
    value_name="Score"
)

In [18]:
melted_df

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [19]:
pivot_df = melted_df.pivot(
    index="Name",
    columns="Subject",
    values="Score"
)

pivot_df

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
Charlie       94    92       89

In [22]:
print(df.columns)

Index(['Name', 'Math', 'Science', 'English'], dtype='object')

In [23]:
melted_df = df.melt(
    id_vars="Name",
    var_name="Subject",
    value_name="Score"
)

melted_df

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [24]:
melted_df.pivot_table(
    index="Name",
    columns="Subject",
    values="Score",
    aggfunc="mean"
)

Subject  English  Math  Science
Name
Alice       88.0  85.0     90.0
Bob         85.0  78.0     82.0
Charlie     94.0  92.0     89.0

In [25]:
df = df.melt(
    id_vars="Name",
    var_name="Subject",
    value_name="Score"
)

In [26]:
df.pivot_table(
    index="Name",
    columns="Subject",
    values="Score",
    aggfunc="mean"
)

Subject  English  Math  Science
Name
Alice       88.0  85.0     90.0
Bob         85.0  78.0     82.0
Charlie     94.0  92.0     89.0